---
name: Search for updates

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update cri-o 1.11 rpm
        run: ./scripts/update.sh
        working-directory: cri-o/1.11
      - name: Update cri-tools 1.11 rpm
        run: ./scripts/update.sh
        working-directory: cri-tools/1.11
      - name: Update git rpm
        run: ./scripts/update.sh
        working-directory: git
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
